name: 'deploy'
description: 'Deploys firebase functions and configs'
inputs:
  firebase_project_id:
    required: true
inputs:
  firebase_functions_env_file:
    required: true
inputs:
  gcp_sa_key:
    required: true
runs:
  using: "composite"
  steps:
      - name: Create env file
        run: |
          cd firebase/functions
          touch .env
          echo "$FIREBASE_FUNCTIONS_ENV_FILE" > .env
        env:
          FIREBASE_FUNCTIONS_ENV_FILE: ${{ inputs.firebase_functions_env_file }}
        shell: bash
      - name: Install npm packages
        run: |
          cd firebase/functions
          npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,firestore
        env:
          GCP_SA_KEY: ${{ inputs.gcp_sa_key }}
          PROJECT_ID: ${{ inputs.firebase_project_id }}