export enum AnalyticsEventEnum {
    InstantSearchRead = "instantsearch-read",
    InstantSearchReadDefaults = "instantsearch-defaults-read",
    InstantSearchLocationAccessEnable = "instantsearch-locationaccess-enable",
    TopicUpdate = "topic-update",
    LoginGoogle = "login-google",
    LoginEmail = "login-email",
    Logout = "logout",
    RegisterGoogle = "register-google",
    RegisterEmail = "register-email",
    PostCreate = "post-create",
    CommentCreate = "comment-create",
    ProfileUpdate = "profile-update",
    ProfileOnboarding = "profile-onboarding",
    ActionCreate = "action-create",
    ActionUpdate = "action-update",
};
