name: Firebase Functions CI/CD - Master

on:
  push:
    branches: [ main-test ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'What environment do you want to deploy to (staging or production)?'
        required: true
        default: 'staging'

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/main-test' && github.event.inputs.environment == 'staging'
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy firebase to staging
        id: deploy
        uses: ./.github/workflows/actions/deploy
        with:
          firebase_project_id: gosolve-mini-staging-test
          firebase_functions_env_file: ${{ secrets.FIREBASE_FUNCTIONS_ENV_FILE }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
  deploy-production:
    if: github.ref == 'refs/heads/main-test' && github.event.inputs.environment == 'production'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy firebase to production
        id: deploy
        uses: ./.github/workflows/actions/deploy
        with:
          firebase_project_id: gosolve-mini-dev-test
          firebase_functions_env_file: ${{ secrets.FIREBASE_FUNCTIONS_ENV_FILE }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
