name: Firebase Functions CI/CD - Develop

on:
  push:
    branches: [ develop ]

jobs:
  create-github-release-tag:
    name: GitHub Tags
    environment: develop
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.taggerFinal.outputs.new_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate Final Version
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: develop
      - name: Echo New Tag
        run: echo "The new tag version will be ${{ steps.taggerFinal.outputs.new_tag }}"
  create-github-release:
    needs: create-github-release-tag
    name: GitHub Release
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ needs.create-github-release-tag.outputs.new_tag }}
          token: ${{ secrets.TOKEN_GITHUB_RELEASE }}
  deploy-sentry:
    needs: [create-github-release-tag, create-github-release]
    name: Sentry Release
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Split Repo Name
        uses: jungwinter/split@v2.1.0
        id: split_repo_name
        with:
          msg: ${{ github.repository }}
          separator: /
          maxsplit: 1
      - name: Sentry Release Web
        uses: getsentry/action-release@v1.4.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
        with:
          environment: development
          version: ${{ steps.split_repo_name.outputs._1 }}@${{ needs.create-github-release-tag.outputs.new_tag }}
      - name: Sentry Release Firebase
        uses: getsentry/action-release@v1.4.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT_FIREBASE }}
        with:
          environment: development
          version: ${{ steps.split_repo_name.outputs._1 }}@${{ needs.create-github-release-tag.outputs.new_tag }}
  deploy-firebase-dev:
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy firebase to develop
        id: deploy
        uses: ./.github/workflows/actions/deploy-firebase
        with:
          firebase_project_id: ${{ vars.FIREBASE_PROJECT_ID }}
          firebase_functions_env_file: ${{ secrets.FIREBASE_FUNCTIONS_ENV_FILE }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
