name: Firebase Functions CI/CD

on:
  push:
    branches: [ main-test, develop-test ]

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop-test'
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: TEST
        run: |
          echo "$GCP_SA_KEY" | cut -b 1-10
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        shell: bash
      - uses: actions/checkout@v2
      - name: Deploy firebase to develop
        id: deploy
        uses: ./.github/workflows/actions/deploy
        with:
          firebase_project_id: gosolve-mini-dev-test
          firebase_functions_env_file: ${{ secrets.FIREBASE_FUNCTIONS_ENV_FILE }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
  deploy-staging:
    if: github.ref == 'refs/heads/main-test'
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy firebase to staging
        id: deploy
        uses: ./.github/workflows/actions/deploy
        with:
          firebase_project_id: gosolve-mini-staging-test
          firebase_functions_env_file: ${{ secrets.FIREBASE_FUNCTIONS_ENV_FILE }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
  deploy-production:
    needs: deploy-staging
    if: github.ref == 'refs/heads/main-test'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy firebase to production
        id: deploy
        uses: ./.github/workflows/actions/deploy
        with:
          firebase_project_id: gosolve-mini-dev-test
          firebase_functions_env_file: ${{ secrets.FIREBASE_FUNCTIONS_ENV_FILE }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
